package model;
// Generated 13/08/2015 16:24:46 by Hibernate Tools 4.3.1



/**
 * Radcheck generated by hbm2java
 */
public class Radcheck  implements java.io.Serializable {


     private int id;
     private String username;
     private String attribute;
     private String op;
     private String value;
     private int reint;
     private String observaciones;

    public Radcheck() {
    }

	
    public Radcheck(int id, String username, String attribute, String op, String value, int reint) {
        this.username = username;
        this.attribute = attribute;
        this.op = op;
        this.value = value;
        this.reint = reint;
    }
    public Radcheck(String username, String attribute, String op, String value, int reint, String observaciones) {
       this.username = username;
       this.attribute = attribute;
       this.op = op;
       this.value = value;
       this.reint = reint;
       this.observaciones = observaciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }
    public String getOp() {
        return this.op;
    }
    
    public void setOp(String op) {
        this.op = op;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public int getReint() {
        return this.reint;
    }
    
    public void setReint(int reint) {
        this.reint = reint;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Override
    public String toString()
    {
        return "Radcheck{" + "id=" + id + ", username=" + username + ", attribute=" + attribute + ", op=" + op + ", value=" + value + ", reint=" + reint + ", observaciones=" + observaciones + '}';
    }
}


