package model;
// Generated 05/08/2015 18:15:36 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Radreply generated by hbm2java
 */
@Entity
@Table(name="radreply"
    ,schema="public"
)
public class Radreply  implements java.io.Serializable {


     private int id;
     private String username;
     private String attribute;
     private String op;
     private String value;

    public Radreply() {
    }

    public Radreply(int id, String username, String attribute, String op, String value) {
       this.id = id;
       this.username = username;
       this.attribute = attribute;
       this.op = op;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=64)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="attribute", nullable=false, length=64)
    public String getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    
    @Column(name="op", nullable=false, length=2)
    public String getOp() {
        return this.op;
    }
    
    public void setOp(String op) {
        this.op = op;
    }

    
    @Column(name="value", nullable=false, length=253)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


